/**
 * Pickup booking form (markup generated by tools/build_site.py).
 * - Pre-selects service/area from ?service=<slug>&area=<slug>
 * - Validates, then opens WhatsApp with a structured booking message.
 * Labels in the message come from each field's data-msg attribute, so the
 * same code serves the English and Hindi forms.
 */
(function () {
  'use strict';

  function pad(n) { return (n < 10 ? '0' : '') + n; }
  function isoDate(d) { return d.getFullYear() + '-' + pad(d.getMonth() + 1) + '-' + pad(d.getDate()); }

  function preselect(select, slug) {
    if (!select || !slug) return;
    for (var i = 0; i < select.options.length; i++) {
      if (select.options[i].getAttribute('data-slug') === slug) { select.selectedIndex = i; return true; }
    }
    return false;
  }

  function digits(v) {
    var d = String(v || '').replace(/\D/g, '');
    if (d.length > 10 && d.indexOf('91') === 0) d = d.slice(d.length - 10);
    return d;
  }

  Array.prototype.forEach.call(document.querySelectorAll('.book-form'), function (form) {
    var params = new URLSearchParams(window.location.search);
    var hadParams = preselect(form.elements.service, params.get('service'));
    hadParams = preselect(form.elements.area, params.get('area')) || hadParams;
    var bagItems = params.get('items');
    if (bagItems && form.elements.notes && !form.elements.notes.value) {
      form.elements.notes.value = bagItems;
      preselect(form.elements.service, 'any');
      hadParams = true;
    }
    if (hadParams && window.location.hash !== '#book') {
      form.scrollIntoView({ block: 'start' });
    }

    var today = new Date();
    form.elements.date.min = isoDate(today);
    if (!form.elements.date.value) {
      var tomorrow = new Date(today.getTime() + 24 * 60 * 60 * 1000);
      form.elements.date.value = isoDate(tomorrow);
    }

    var errorBox = form.querySelector('.book-error');

    function showMessage(msg, ok) {
      errorBox.textContent = msg;
      errorBox.classList.toggle('is-ok', !!ok);
      errorBox.hidden = false;
    }

    form.addEventListener('submit', function (ev) {
      ev.preventDefault();
      errorBox.hidden = true;

      var missing = [];
      ['name', 'phone', 'area', 'address', 'date'].forEach(function (n) {
        var el = form.elements[n];
        el.removeAttribute('aria-invalid');
        if (!String(el.value).trim()) { missing.push(el.getAttribute('data-msg')); el.setAttribute('aria-invalid', 'true'); }
      });
      if (missing.length) {
        showMessage(form.getAttribute('data-err-required') + ' ' + missing.join(', '));
        return;
      }
      var phone = digits(form.elements.phone.value);
      if (!/^[6-9]\d{9}$/.test(phone)) {
        form.elements.phone.setAttribute('aria-invalid', 'true');
        showMessage(form.getAttribute('data-err-phone'));
        return;
      }

      var lines = [form.getAttribute('data-intro'), ''];
      ['service', 'name', 'phone', 'area', 'address', 'date', 'time', 'notes'].forEach(function (n) {
        var el = form.elements[n];
        var v = n === 'phone' ? phone : String(el.value).trim();
        if (n === 'date' && v) {
          var d = new Date(v + 'T00:00:00');
          v = d.toLocaleDateString(document.documentElement.lang || 'en-IN', { weekday: 'short', day: 'numeric', month: 'short' });
        }
        if (v) lines.push(el.getAttribute('data-msg') + ': ' + v);
      });

      var url = 'https://wa.me/' + form.getAttribute('data-wa') + '?text=' + encodeURIComponent(lines.join('\n'));
      // Note: passing 'noopener' makes window.open return null, which would
      // trigger the fallback every time — so detach the opener manually.
      var win = window.open(url, '_blank');
      if (win) { win.opener = null; } else { window.location.href = url; }
      showMessage(form.getAttribute('data-sent'), true);
    });
  });
})();
