/**
 * Price estimator on pricing.html. Markup (rows, prices, thresholds) is
 * generated by tools/build_site.py from data/prices.json — this file only
 * does the arithmetic and builds the WhatsApp message.
 */
(function () {
  'use strict';
  var root = document.querySelector('.calc');
  if (!root) return;

  var freeMin = Number(root.getAttribute('data-free-min')) || 0;
  var firstOff = Number(root.getAttribute('data-first-off')) || 0;
  var waNumber = root.getAttribute('data-wa');
  var rows = Array.prototype.slice.call(root.querySelectorAll('.calc-row'));
  var out = {};
  Array.prototype.forEach.call(root.querySelectorAll('[data-out]'), function (el) {
    out[el.getAttribute('data-out')] = el;
  });

  function rupees(n) {
    return '₹' + Math.round(n).toLocaleString('en-IN');
  }

  function update() {
    var total = 0, pieces = 0, kg = 0, anyFrom = false, lines = [];
    rows.forEach(function (row) {
      var qty = Number(row.getAttribute('data-qty')) || 0;
      if (!qty) return;
      var price = Number(row.getAttribute('data-price'));
      var unit = row.getAttribute('data-unit');
      var from = row.getAttribute('data-from') === '1';
      var cost = qty * price;
      total += cost;
      if (unit === 'kg') { kg += qty; } else { pieces += qty; }
      if (from) anyFrom = true;
      lines.push('- ' + qty + (unit === 'kg' ? ' kg ' : ' x ') + row.getAttribute('data-label') +
                 ' (' + rupees(cost) + (from ? '+' : '') + ')');
    });

    var parts = [];
    if (pieces) parts.push(pieces + (pieces === 1 ? ' piece' : ' pieces'));
    if (kg) parts.push(kg + ' kg');
    out.count.textContent = parts.length ? parts.join(' + ') : '0';
    out.total.textContent = rupees(total) + (anyFrom ? '+' : '');
    if (!total) {
      out.pickup.textContent = 'Free above ' + rupees(freeMin);
    } else if (total >= freeMin) {
      out.pickup.textContent = 'FREE';
    } else {
      out.pickup.textContent = 'Add ' + rupees(freeMin - total) + ' more for free pickup';
    }
    out.first.textContent = rupees(total * (100 - firstOff) / 100) + (anyFrom ? '+' : '');

    var msg = 'Hi Cleanzit, I\'d like to book a pickup.';
    if (lines.length) {
      msg += '\n\nMy items:\n' + lines.join('\n') + '\n\nEstimated total: ' + rupees(total) + (anyFrom ? '+' : '');
    }
    out.wa.setAttribute('href', 'https://wa.me/' + waNumber + '?text=' + encodeURIComponent(msg));
  }

  rows.forEach(function (row) {
    var output = row.querySelector('output');
    row.addEventListener('click', function (ev) {
      var btn = ev.target.closest('button[data-step]');
      if (!btn) return;
      var qty = Math.min(99, Math.max(0, (Number(row.getAttribute('data-qty')) || 0) + Number(btn.getAttribute('data-step'))));
      row.setAttribute('data-qty', qty);
      output.textContent = qty;
      row.classList.toggle('has-qty', qty > 0);
      update();
    });
  });
  update();
})();
